### ISSUE TITLE
Questions about the parameter matched.clusters?

### ISSUE THREAD

**Issue by XiHuYan** [yycunc/iSMNN#3]
1. Does matched.clusters mean the set of shared cluster.labels among all batches?

2. What if I have three batches that their intersection of cluster.labels is empty?

**Comment by yycunc** [comment]
Hi, thanks for your question, and sorry for my late response. Yes, iSMNN first matches the clusters across batches and then used the matched clusters to define mutual nearest neighbors among batches and batch effect correction.

For iSMNN, as well as the original MNN and Seurat, at least one cell type should be shared among batches, because without shared cell type/cluster, there is no way to distinguish the true biological variance from batch effects.
